FeatureExtraction: "ResNet"
PAD: false
Prediction: "Attn"
SequenceModeling: "BiLSTM"
Transformation: "TPS"
batch_max_length: 25
batch_size: 192
character: "0123456789abcdefghijklmnopqrstuvwxyz"
hidden_size: 256
imgH: 32
imgW: 100
input_channel: 1
num_fiducial: 20
num_gpu: 1
output_channel: 512
rgb: false
sensitive: false
workers: 1
